# Generated by Django 3.2.5 on 2021-07-11 15:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefield', cloudinary.models.CloudinaryField(max_length=255)),
                ('Tittle', models.TextField()),
                ('subtitle', models.TextField()),
                ('button_url', models.URLField()),
            ],
        ),
    ]
