# Generated by Django 3.2.5 on 2021-07-11 16:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefield', cloudinary.models.CloudinaryField(max_length=255)),
                ('Tittle', models.TextField()),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefield', cloudinary.models.CloudinaryField(max_length=255)),
                ('Tittle', models.TextField()),
                ('subtitle', models.TextField()),
            ],
        ),
    ]
